version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8080"

    container_name: user-service
