-- ============================================================
-- V1 — Initial schema
-- Reflects entities as generated by Hibernate with
-- spring.jpa.hibernate.ddl-auto=update (Spring Boot 3 / MySQL 8)
-- ============================================================

CREATE TABLE IF NOT EXISTS users
(
    id                    BINARY(16)   NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(100) NOT NULL,
    phone_country_code    VARCHAR(4)   NOT NULL,
    phone_number          VARCHAR(15)  NOT NULL,
    document_type         VARCHAR(100),
    document_number       VARCHAR(100),
    street                VARCHAR(500) NOT NULL,
    street_number         VARCHAR(500),
    city                  VARCHAR(100) NOT NULL,
    state                 VARCHAR(100) NOT NULL,
    postal_code           VARCHAR(100) NOT NULL,
    country               VARCHAR(100) NOT NULL,
    secret_key            VARCHAR(100) NOT NULL,
    password              VARCHAR(255),
    failed_login_attempts INT,
    created_at            DATETIME(6),
    status                VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_roles
(
    id      BINARY(16)   NOT NULL,
    user_id BINARY(16)   NOT NULL,
    role    VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS password_reset_tokens
(
    id              BINARY(16)   NOT NULL,
    user_id         BINARY(16)   NOT NULL,
    token           VARCHAR(255) NOT NULL,
    expiration_date DATETIME(6)  NOT NULL,
    is_used         TINYINT(1)   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS outbox_events
(
    id          BINARY(16)   NOT NULL,
    event_type  VARCHAR(255) NOT NULL,
    payload     VARCHAR(255) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    created_at  DATETIME(6)  NOT NULL,
    queue       VARCHAR(255) NOT NULL,
    routing_key VARCHAR(255) NOT NULL,
    exchange    VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Index used by the outbox processor to poll PENDING events efficiently
CREATE INDEX idx_outbox_events_status ON outbox_events (status);

CREATE TABLE IF NOT EXISTS user_action_log
(
    id          BINARY(16)    NOT NULL,
    user_id     BINARY(16)    NOT NULL,
    user_action VARCHAR(255)  NOT NULL,
    timestamp   DATETIME(6)   NOT NULL,
    metadata    VARCHAR(10000),
    PRIMARY KEY (id),
    CONSTRAINT fk_ual_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;